/**
 * Codex AGENTS.md assembly: per-space instruction block rendering and the
 * praesidium-context block editor that injects runtime system-prompt content.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

export const CODEX_AGENTS_FILE = 'AGENTS.md'

const PRAESIDIUM_BEGIN_MARKER = '<!-- BEGIN praesidium-context -->'
const PRAESIDIUM_END_MARKER = '<!-- END praesidium-context -->'

export function buildAgentsMarkdown(
  blocks: Array<{ spaceId: string; version: string; content: string }>
): string {
  const lines: string[] = ['<!-- Generated by agent-spaces. -->']

  for (const block of blocks) {
    lines.push('')
    lines.push(`<!-- BEGIN space: ${block.spaceId}@${block.version} -->`)
    lines.push(block.content.trimEnd())
    lines.push(`<!-- END space: ${block.spaceId}@${block.version} -->`)
  }

  lines.push('')
  return lines.join('\n')
}

export interface PraesidiumContext {
  systemPrompt?: string | undefined
  reminderContent?: string | undefined
}

/**
 * Render the praesidium-context block (delimited by the BEGIN/END markers) from
 * the materialized system prompt + session reminder. Returns `undefined` when
 * there is no content to inject. This is the single source of truth for the
 * exact bytes written into AGENTS.md, so callers that need to fingerprint the
 * home prompt material (run-codex) hash this string and get byte-for-byte
 * agreement with what `applyPraesidiumContextToCodexHome` writes.
 */
export function renderPraesidiumContextBlock(context: PraesidiumContext): string | undefined {
  const systemPrompt = context.systemPrompt?.trim() ?? ''
  const reminderContent = context.reminderContent?.trim() ?? ''
  if (!systemPrompt && !reminderContent) {
    return undefined
  }

  const sections: string[] = []
  if (systemPrompt) {
    sections.push(systemPrompt)
  }
  if (reminderContent) {
    sections.push(reminderContent)
  }

  return [PRAESIDIUM_BEGIN_MARKER, sections.join('\n\n'), PRAESIDIUM_END_MARKER].join('\n')
}

/**
 * Write praesidium-materialized system prompt + reminder content into a runtime
 * codex home's AGENTS.md so codex picks it up via its native user_instructions
 * load path. Replaces any existing praesidium-context block on each call so
 * repeated runs don't accumulate stale content.
 *
 * Codex's base_instructions are not touched — this only adds to the
 * AGENTS.md that becomes config.user_instructions inside codex.
 */
export async function applyPraesidiumContextToCodexHome(
  codexHome: string,
  context: PraesidiumContext
): Promise<boolean> {
  const agentsPath = join(codexHome, CODEX_AGENTS_FILE)
  let existing = ''
  try {
    existing = await readFile(agentsPath, 'utf-8')
  } catch {
    // No existing AGENTS.md (e.g. ad-hoc bundle); start fresh.
    existing = ''
  }

  // Strip any prior praesidium block so we always emit fresh content.
  const stripped = stripPraesidiumBlock(existing).trimEnd()
  const block = renderPraesidiumContextBlock(context)
  if (block === undefined) {
    if (stripped !== existing.trimEnd()) {
      await writeFile(agentsPath, stripped.length > 0 ? `${stripped}\n` : '')
      return true
    }
    return false
  }

  const next = stripped.length > 0 ? `${stripped}\n\n${block}\n` : `${block}\n`
  await writeFile(agentsPath, next)
  return true
}

function stripPraesidiumBlock(content: string): string {
  let remaining = content
  while (true) {
    const beginIdx = remaining.indexOf(PRAESIDIUM_BEGIN_MARKER)
    if (beginIdx === -1) {
      return remaining
    }
    const endIdx = remaining.indexOf(PRAESIDIUM_END_MARKER, beginIdx)
    if (endIdx === -1) {
      return remaining
    }
    remaining =
      remaining.slice(0, beginIdx) + remaining.slice(endIdx + PRAESIDIUM_END_MARKER.length)
  }
}
