export type {
  ExpectedPredecessor,
  HrcSocketPath,
  JoinArgs,
  JoinAttachAttached,
  JoinAttachRefused,
  JoinAttachRequest,
  JoinAttachResult,
  JoinPrepareInput,
  JoinRegisterRefused,
  JoinRegisterRegistered,
  JoinRegisterRequest,
  JoinResult,
  RegisteredIdentity,
} from './types'
export {
  attachParticipant,
  isAttachConflict,
  isAttachEpochStale,
  isHostBindingConflict,
  isIncarnationBoundElsewhere,
  isRedirect,
  isScopeOccupied,
  isScopeRetired,
  joinAsParticipant,
  registerParticipant,
} from './client'
