/**
 * Muse workspace composer (spike 1 pure functions).
 *
 * Composes ordered space snapshot directories into a deterministic
 * `<bundle>/muse.workspace/` bundle: concatenated AGENTS.md, merged skills/,
 * generated settings.json (space `mcp/mcp.json` merged via
 * `composeMcpFromSpaces`, collisions surface as `W_MCP` warnings), and a
 * Codex-schema manifest.json.
 *
 * Spike-1 stability notes (allowed to churn through spikes 8-10 without
 * touching any public surface — there is none yet: no adapter, no
 * `register()`, no `HarnessId`):
 * - `settings.json` is the minimal `{ mcpServers }` shape; muse-native
 *   settings resolution is spike 9.
 * - `manifest.json` carries no timestamp so two composes of the same input
 *   are byte-identical; `fingerprint` is the canonical-hash of the manifest
 *   material.
 * - Skill discovery reads `skills/`, `.muse/skills/`, and
 *   `.config/muse/skills/` in that order (project-scope discovery is spike 8,
 *   the long pole); later spaces win on name collisions.
 */
import { createHash } from 'node:crypto'
import { constants, access, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { composeMcpFromSpaces, copyDir } from 'spaces-config'
import { createCanonicalHasher } from 'spaces-runtime-contracts'

export const MUSE_WORKSPACE_DIRNAME = 'muse.workspace'
export const MUSE_AGENTS_FILE = 'AGENTS.md'
export const MUSE_SKILLS_DIR = 'skills'
export const MUSE_SETTINGS_FILE = 'settings.json'
export const MUSE_MANIFEST_FILE = 'manifest.json'

const SPACE_INSTRUCTIONS_FILES = ['AGENTS.md', 'AGENT.md', 'instructions.md'] as const
const SPACE_SKILL_DIR_CANDIDATES = ['skills', '.muse/skills', '.config/muse/skills'] as const

export interface MuseSpaceSource {
  spaceId: string
  version?: string | undefined
  dir: string
}

export interface ComposeMuseWorkspaceInput {
  targetName: string
  spaces: MuseSpaceSource[]
}

export interface MuseComposerWarning {
  code: 'W_MCP' | 'W_SKILL'
  message: string
}

export interface MuseWorkspaceFingerprint {
  algorithm: 'sha256-canonical-json/v1'
  value: string
}

export interface MuseWorkspaceBundle {
  rootDir: string
  workspaceDir: string
  agentsPath: string
  skillsDir: string
  settingsPath: string
  manifestPath: string
  fingerprint: MuseWorkspaceFingerprint
}

export interface ComposeMuseWorkspaceResult {
  bundle: MuseWorkspaceBundle
  warnings: MuseComposerWarning[]
}

export interface ComposeMuseWorkspaceOptions {
  clean?: boolean | undefined
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

async function isDirectory(path: string): Promise<boolean> {
  try {
    const stats = await stat(path)
    return stats.isDirectory()
  } catch {
    return false
  }
}

function hashContent(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

export function buildMuseAgentsMarkdown(
  blocks: Array<{ spaceId: string; version: string; content: string }>
): string {
  const lines: string[] = ['<!-- Generated by agent-spaces. -->']
  for (const block of blocks) {
    lines.push('')
    lines.push(`<!-- BEGIN space: ${block.spaceId}@${block.version} -->`)
    lines.push(block.content.trimEnd())
    lines.push(`<!-- END space: ${block.spaceId}@${block.version} -->`)
  }
  lines.push('')
  return lines.join('\n')
}

async function readSpaceInstructions(dir: string): Promise<string | null> {
  for (const filename of SPACE_INSTRUCTIONS_FILES) {
    const path = join(dir, filename)
    if (await fileExists(path)) {
      return await readFile(path, 'utf-8')
    }
  }
  return null
}

function parseFrontmatterField(content: string, field: 'name' | 'description'): string | null {
  if (!content.startsWith('---')) return null
  const end = content.indexOf('---', 3)
  if (end === -1) return null
  const frontmatter = content.slice(3, end)
  for (const line of frontmatter.split('\n')) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(.+?)\s*$/)
    if (match?.[1] === field) {
      const raw = match[2] ?? ''
      return raw.replace(/^['"]|['"]$/g, '').trim() || null
    }
  }
  return null
}

async function lintSkillPackage(skillsDir: string, skillName: string): Promise<string | null> {
  const skillFile = join(skillsDir, skillName, 'SKILL.md')
  if (!(await fileExists(skillFile))) {
    return `Skill "${skillName}" missing SKILL.md`
  }
  const content = await readFile(skillFile, 'utf-8')
  const name = parseFrontmatterField(content, 'name')
  const description = parseFrontmatterField(content, 'description')
  if (!name || !description) {
    return `Skill "${skillName}" invalid-skill-package: SKILL.md frontmatter requires name + description`
  }
  return null
}

export interface MuseManifest {
  schemaVersion: 1
  producer: 'muse-serve'
  targetName: string
  spaces: Array<{ spaceId: string; version: string }>
  skills: string[]
  mcpServers: string[]
  instructions: Array<{ spaceId: string; version: string; hash: string }>
}

function sortStrings(values: Set<string> | string[]): string[] {
  return Array.from(values).sort()
}

/**
 * Compose ordered space snapshots into `<outputDir>/muse.workspace/`.
 * Deterministic: same input order + same bytes in → same bytes out (no
 * timestamps anywhere in the bundle).
 */
export async function composeMuseWorkspace(
  input: ComposeMuseWorkspaceInput,
  outputDir: string,
  options: ComposeMuseWorkspaceOptions = {}
): Promise<ComposeMuseWorkspaceResult> {
  const warnings: MuseComposerWarning[] = []
  if (options.clean) {
    await rm(outputDir, { recursive: true, force: true })
  }

  const workspaceDir = join(outputDir, MUSE_WORKSPACE_DIRNAME)
  const skillsDir = join(workspaceDir, MUSE_SKILLS_DIR)
  await mkdir(workspaceDir, { recursive: true })
  await mkdir(skillsDir, { recursive: true })

  const instructionsBlocks: Array<{ spaceId: string; version: string; content: string }> = []
  const instructionsHashes: Array<{ spaceId: string; version: string; hash: string }> = []
  const mergedSkills = new Set<string>()

  for (const space of input.spaces) {
    const version = space.version ?? 'unknown'
    const instructions = await readSpaceInstructions(space.dir)
    if (instructions !== null) {
      instructionsBlocks.push({ spaceId: space.spaceId, version, content: instructions })
      instructionsHashes.push({ spaceId: space.spaceId, version, hash: hashContent(instructions) })
    }

    for (const candidate of SPACE_SKILL_DIR_CANDIDATES) {
      const srcSkillsDir = join(space.dir, candidate)
      if (!(await isDirectory(srcSkillsDir))) continue
      const entries = (await readdir(srcSkillsDir, { withFileTypes: true })).sort((left, right) =>
        left.name < right.name ? -1 : left.name > right.name ? 1 : 0
      )
      for (const entry of entries) {
        const srcPath = join(srcSkillsDir, entry.name)
        const isDirEntry =
          entry.isDirectory() || (entry.isSymbolicLink() && (await isDirectory(srcPath)))
        if (!isDirEntry) continue
        const destPath = join(skillsDir, entry.name)
        await rm(destPath, { recursive: true, force: true })
        await copyDir(srcPath, destPath, { useHardlinks: false })
        mergedSkills.add(entry.name)
      }
    }
  }

  for (const skillName of sortStrings(mergedSkills)) {
    const problem = await lintSkillPackage(skillsDir, skillName)
    if (problem) {
      warnings.push({ code: 'W_SKILL', message: problem })
    }
  }

  const agentsPath = join(workspaceDir, MUSE_AGENTS_FILE)
  const agentsContent = buildMuseAgentsMarkdown(instructionsBlocks)
  await writeFile(agentsPath, agentsContent)

  const settingsPath = join(workspaceDir, MUSE_SETTINGS_FILE)
  const { config: mcpConfig, warnings: mcpWarnings } = await composeMcpFromSpaces(
    input.spaces.map((space) => ({ spaceId: space.spaceId, dir: space.dir })),
    settingsPath
  )
  for (const warning of mcpWarnings) {
    warnings.push({ code: 'W_MCP', message: warning })
  }
  if (!(await fileExists(settingsPath))) {
    await writeFile(settingsPath, '{\n  "mcpServers": {}\n}\n')
  }

  const manifest: MuseManifest = {
    schemaVersion: 1,
    producer: 'muse-serve',
    targetName: input.targetName,
    spaces: input.spaces.map((space) => ({
      spaceId: space.spaceId,
      version: space.version ?? 'unknown',
    })),
    skills: sortStrings(mergedSkills),
    mcpServers: sortStrings(Object.keys(mcpConfig.mcpServers)),
    instructions: instructionsHashes,
  }
  const manifestPath = join(workspaceDir, MUSE_MANIFEST_FILE)
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)

  const hasher = createCanonicalHasher()
  const fingerprint = hasher.hash(manifest) as MuseWorkspaceFingerprint

  return {
    bundle: {
      rootDir: outputDir,
      workspaceDir,
      agentsPath,
      skillsDir,
      settingsPath,
      manifestPath,
      fingerprint,
    },
    warnings,
  }
}

/**
 * `loadTargetBundle`-style readback: assert the bundle layout and return the
 * bundle descriptor for the caller's target. Throws verbatim when the layout
 * is wrong; part of observable behavior.
 */
export async function loadMuseWorkspaceBundle(
  outputDir: string,
  targetName: string
): Promise<MuseWorkspaceBundle> {
  const workspaceDir = join(outputDir, MUSE_WORKSPACE_DIRNAME)
  const agentsPath = join(workspaceDir, MUSE_AGENTS_FILE)
  const skillsDir = join(workspaceDir, MUSE_SKILLS_DIR)
  const settingsPath = join(workspaceDir, MUSE_SETTINGS_FILE)
  const manifestPath = join(workspaceDir, MUSE_MANIFEST_FILE)

  if (!(await isDirectory(workspaceDir))) {
    throw new Error(`Muse workspace directory not found: ${workspaceDir}`)
  }
  if (!(await fileExists(agentsPath))) {
    throw new Error(`Muse AGENTS.md not found: ${agentsPath}`)
  }
  if (!(await fileExists(manifestPath))) {
    throw new Error(`Muse manifest.json not found: ${manifestPath}`)
  }

  const manifestRaw = await readFile(manifestPath, 'utf-8')
  const manifest = JSON.parse(manifestRaw) as MuseManifest
  if (manifest.targetName !== targetName) {
    throw new Error(
      `Muse bundle target mismatch: expected ${targetName}, found ${manifest.targetName}`
    )
  }
  const hasher = createCanonicalHasher()
  const fingerprint = hasher.hash(manifest) as MuseWorkspaceFingerprint

  return {
    rootDir: outputDir,
    workspaceDir,
    agentsPath,
    skillsDir,
    settingsPath,
    manifestPath,
    fingerprint,
  }
}
