#!/usr/bin/env bun
/**
 * Sync the agent-spaces-manager space from its canonical copy.
 *
 * WHY: The live manager space is `<agents-root>/spaces/agent-spaces-manager`
 * (spaces load from the agents root since T-04144). agent-spaces carries two
 * derived copies: `spaces/agent-spaces-manager/` and the embedded module that
 * `asp repo init` writes (the CLI publishes dist/ only, so it cannot read the
 * agents root at runtime). Both are generated from the canonical tree here so
 * they cannot fork from it again (T-10369).
 *
 * Usage:
 *   bun scripts/sync-manager-space.ts            # copy + regenerate
 *   bun scripts/sync-manager-space.ts --check    # exit 1 if either copy drifted
 *   bun scripts/sync-manager-space.ts --source <dir>
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, relative, resolve } from 'node:path'

const REPO_ROOT = resolve(import.meta.dir, '..')
const SPACE_ID = 'agent-spaces-manager'
const SPACES_COPY = join(REPO_ROOT, 'spaces', SPACE_ID)
const GENERATED_MODULE = join(
  REPO_ROOT,
  'apps/cli/src/commands/repo/manager-space/files.generated.ts'
)

interface CanonicalFile {
  path: string
  content: string
  executable: boolean
}

function defaultSource(): string {
  const agentsRoot =
    process.env['ASP_AGENTS_ROOT'] || join(homedir(), 'praesidium', 'var', 'agents')
  return join(agentsRoot, 'spaces', SPACE_ID)
}

function listTree(dir: string): string[] {
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name !== '.DS_Store')
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)))
    .sort()
}

function readTree(dir: string): CanonicalFile[] {
  return listTree(dir).map((path) => {
    const full = join(dir, path)
    return {
      path,
      content: readFileSync(full, 'utf8'),
      executable: (statSync(full).mode & 0o111) !== 0,
    }
  })
}

function templateLiteral(content: string): string {
  return `\`${content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\``
}

function renderModule(files: CanonicalFile[]): string {
  const entries = files.map((file) => {
    const lines = ['  {', `    path: '${file.path}',`]
    if (file.executable) lines.push('    executable: true,')
    lines.push(`    content: ${templateLiteral(file.content)},`, '  },')
    return lines.join('\n')
  })
  return `// GENERATED by \`just sync-manager-space\` (scripts/sync-manager-space.ts) from
// <agents-root>/spaces/${SPACE_ID}. DO NOT EDIT BY HAND: edit the canonical
// space in the agents repo, then re-run the sync.

import type { SpaceFile } from '../manager-space-content'

export const MANAGER_SPACE_FILES: SpaceFile[] = [
${entries.join('\n')}
]
`
}

function spacesCopyDrift(files: CanonicalFile[]): string[] {
  const drift: string[] = []
  const onDisk = existsSync(SPACES_COPY) ? listTree(SPACES_COPY) : []
  const wanted = new Set(files.map((file) => file.path))
  for (const path of onDisk) if (!wanted.has(path)) drift.push(`extra spaces/${SPACE_ID}/${path}`)
  for (const file of files) {
    const full = join(SPACES_COPY, file.path)
    if (!existsSync(full)) {
      drift.push(`missing spaces/${SPACE_ID}/${file.path}`)
    } else if (readFileSync(full, 'utf8') !== file.content) {
      drift.push(`content spaces/${SPACE_ID}/${file.path}`)
    } else if (((statSync(full).mode & 0o111) !== 0) !== file.executable) {
      drift.push(`mode spaces/${SPACE_ID}/${file.path}`)
    }
  }
  return drift
}

function writeSpacesCopy(files: CanonicalFile[]): void {
  rmSync(SPACES_COPY, { recursive: true, force: true })
  for (const file of files) {
    const full = join(SPACES_COPY, file.path)
    mkdirSync(dirname(full), { recursive: true })
    writeFileSync(full, file.content)
    chmodSync(full, file.executable ? 0o755 : 0o644)
  }
}

function main(): void {
  const args = process.argv.slice(2)
  const check = args.includes('--check')
  const sourceIndex = args.indexOf('--source')
  const source = resolve(sourceIndex >= 0 ? (args[sourceIndex + 1] ?? '') : defaultSource())

  if (!existsSync(join(source, 'space.toml'))) {
    console.error(`[sync-manager-space] canonical space not found: ${source}`)
    process.exit(2)
  }

  const files = readTree(source)
  const module = renderModule(files)

  if (check) {
    const drift = spacesCopyDrift(files)
    const current = existsSync(GENERATED_MODULE) ? readFileSync(GENERATED_MODULE, 'utf8') : ''
    if (current !== module) drift.push(`content ${relative(REPO_ROOT, GENERATED_MODULE)}`)
    if (drift.length > 0) {
      console.error(`[sync-manager-space] drift from ${source}:`)
      for (const line of drift) console.error(`  ${line}`)
      console.error('[sync-manager-space] run `just sync-manager-space` to regenerate.')
      process.exit(1)
    }
    console.log(`[sync-manager-space] in sync with ${source} (${files.length} files)`)
    return
  }

  writeSpacesCopy(files)
  mkdirSync(dirname(GENERATED_MODULE), { recursive: true })
  writeFileSync(GENERATED_MODULE, module)
  console.log(`[sync-manager-space] synced ${files.length} files from ${source}`)
}

if (import.meta.main) main()
