#!/usr/bin/env bun
/**
 * Sync the agent-spaces-manager space from its canonical copy.
 *
 * WHY: The live manager space is `<agents-root>/spaces/agent-spaces-manager`
 * (spaces load from the agents root since T-04144). agent-spaces carries two
 * derived copies: `spaces/agent-spaces-manager/` and the embedded module that
 * `asp repo init` writes (the CLI publishes dist/ only, so it cannot read the
 * agents root at runtime). Both are generated from the canonical tree here so
 * they cannot fork from it again (T-10369).
 *
 * Usage:
 *   bun scripts/sync-manager-space.ts            # copy + regenerate
 *   bun scripts/sync-manager-space.ts --check    # exit 1 if either copy drifted
 *   bun scripts/sync-manager-space.ts --source <dir>
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, relative, resolve } from 'node:path'

const REPO_ROOT = resolve(import.meta.dir, '..')
const SPACE_ID = 'agent-spaces-manager'
const SPACES_COPY = join(REPO_ROOT, 'spaces', SPACE_ID)
// One generated module per canonical file plus a generated index listing them
// in canonical order, so no generated file outgrows the file-loc budget (T-10402).
const GENERATED_DIR = join(REPO_ROOT, 'apps/cli/src/commands/repo/manager-space/generated')
const GENERATED_INDEX = 'index.generated.ts'
const LEGACY_MODULE = join(REPO_ROOT, 'apps/cli/src/commands/repo/manager-space/files.generated.ts')
const GENERATED_HEADER = `// GENERATED by \`just sync-manager-space\` (scripts/sync-manager-space.ts) from
// <agents-root>/spaces/${SPACE_ID}. DO NOT EDIT BY HAND: edit the canonical
// space in the agents repo, then re-run the sync.
`

interface CanonicalFile {
  path: string
  content: string
  executable: boolean
}

function defaultSource(): string {
  const agentsRoot =
    process.env['ASP_AGENTS_ROOT'] || join(homedir(), 'praesidium', 'var', 'agents')
  return join(agentsRoot, 'spaces', SPACE_ID)
}

function listTree(dir: string): string[] {
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name !== '.DS_Store')
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)))
    .sort()
}

function readTree(dir: string): CanonicalFile[] {
  return listTree(dir).map((path) => {
    const full = join(dir, path)
    return {
      path,
      content: readFileSync(full, 'utf8'),
      executable: (statSync(full).mode & 0o111) !== 0,
    }
  })
}

function templateLiteral(content: string): string {
  return `\`${content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\``
}

/** `commands/add-hook.md` -> `commands-add-hook-md` */
function moduleSlug(path: string): string {
  return path.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function renderFileModule(file: CanonicalFile): string {
  const lines = [
    GENERATED_HEADER,
    "import type { SpaceFile } from '../../manager-space-content'",
    '',
    'export const SPACE_FILE: SpaceFile = {',
    `  path: '${file.path}',`,
  ]
  if (file.executable) lines.push('  executable: true,')
  lines.push(`  content: ${templateLiteral(file.content)},`, '}', '')
  return lines.join('\n')
}

/** Every generated module (file name -> content), index included. */
function renderModules(files: CanonicalFile[]): Map<string, string> {
  const modules = new Map<string, string>()
  const imports: string[] = []
  const names: string[] = []
  files.forEach((file, index) => {
    const slug = moduleSlug(file.path)
    const name = `${slug}.generated.ts`
    if (modules.has(name) || name === GENERATED_INDEX) {
      throw new Error(`[sync-manager-space] module name collision for ${file.path}: ${name}`)
    }
    modules.set(name, renderFileModule(file))
    imports.push(`import { SPACE_FILE as file${index} } from './${slug}.generated'`)
    names.push(`  file${index},`)
  })
  // Sorted so biome's organizeImports accepts the generated index as-is.
  imports.sort((a, b) => (a.split("'")[1] ?? '').localeCompare(b.split("'")[1] ?? ''))
  modules.set(
    GENERATED_INDEX,
    [
      GENERATED_HEADER,
      "import type { SpaceFile } from '../../manager-space-content'",
      ...imports,
      '',
      '/** The manager space files in canonical (sorted path) order. */',
      'export const MANAGER_SPACE_FILES: SpaceFile[] = [',
      ...names,
      ']',
      '',
    ].join('\n')
  )
  return modules
}

function generatedDrift(modules: Map<string, string>): string[] {
  const drift: string[] = []
  const dirLabel = relative(REPO_ROOT, GENERATED_DIR)
  if (existsSync(LEGACY_MODULE)) drift.push(`extra ${relative(REPO_ROOT, LEGACY_MODULE)}`)
  const onDisk = existsSync(GENERATED_DIR) ? listTree(GENERATED_DIR) : []
  for (const name of onDisk) if (!modules.has(name)) drift.push(`extra ${dirLabel}/${name}`)
  for (const [name, content] of modules) {
    const full = join(GENERATED_DIR, name)
    if (!existsSync(full)) drift.push(`missing ${dirLabel}/${name}`)
    else if (readFileSync(full, 'utf8') !== content) drift.push(`content ${dirLabel}/${name}`)
  }
  return drift
}

function writeGenerated(modules: Map<string, string>): void {
  rmSync(LEGACY_MODULE, { force: true })
  rmSync(GENERATED_DIR, { recursive: true, force: true })
  mkdirSync(GENERATED_DIR, { recursive: true })
  for (const [name, content] of modules) writeFileSync(join(GENERATED_DIR, name), content)
}

function spacesCopyDrift(files: CanonicalFile[]): string[] {
  const drift: string[] = []
  const onDisk = existsSync(SPACES_COPY) ? listTree(SPACES_COPY) : []
  const wanted = new Set(files.map((file) => file.path))
  for (const path of onDisk) if (!wanted.has(path)) drift.push(`extra spaces/${SPACE_ID}/${path}`)
  for (const file of files) {
    const full = join(SPACES_COPY, file.path)
    if (!existsSync(full)) {
      drift.push(`missing spaces/${SPACE_ID}/${file.path}`)
    } else if (readFileSync(full, 'utf8') !== file.content) {
      drift.push(`content spaces/${SPACE_ID}/${file.path}`)
    } else if (((statSync(full).mode & 0o111) !== 0) !== file.executable) {
      drift.push(`mode spaces/${SPACE_ID}/${file.path}`)
    }
  }
  return drift
}

function writeSpacesCopy(files: CanonicalFile[]): void {
  rmSync(SPACES_COPY, { recursive: true, force: true })
  for (const file of files) {
    const full = join(SPACES_COPY, file.path)
    mkdirSync(dirname(full), { recursive: true })
    writeFileSync(full, file.content)
    chmodSync(full, file.executable ? 0o755 : 0o644)
  }
}

function main(): void {
  const args = process.argv.slice(2)
  const check = args.includes('--check')
  const sourceIndex = args.indexOf('--source')
  const source = resolve(sourceIndex >= 0 ? (args[sourceIndex + 1] ?? '') : defaultSource())

  if (!existsSync(join(source, 'space.toml'))) {
    console.error(`[sync-manager-space] canonical space not found: ${source}`)
    process.exit(2)
  }

  const files = readTree(source)
  const modules = renderModules(files)

  if (check) {
    const drift = [...spacesCopyDrift(files), ...generatedDrift(modules)]
    if (drift.length > 0) {
      console.error(`[sync-manager-space] drift from ${source}:`)
      for (const line of drift) console.error(`  ${line}`)
      console.error('[sync-manager-space] run `just sync-manager-space` to regenerate.')
      process.exit(1)
    }
    console.log(`[sync-manager-space] in sync with ${source} (${files.length} files)`)
    return
  }

  writeSpacesCopy(files)
  writeGenerated(modules)
  console.log(`[sync-manager-space] synced ${files.length} files from ${source}`)
}

if (import.meta.main) main()
