// GENERATED by `just sync-manager-space` (scripts/sync-manager-space.ts) from
// <agents-root>/spaces/agent-spaces-manager. DO NOT EDIT BY HAND: edit the canonical
// space in the agents repo, then re-run the sync.

import type { SpaceFile } from '../manager-space-content'

export const MANAGER_SPACE_FILES: SpaceFile[] = [
  {
    path: 'agents/manager.md',
    content: `# Agent Spaces Manager Agent

Coordinator agent for space authoring and project composition workflows.

## Role

I am the Agent Spaces Manager - I help you create and manage spaces in the shared spaces root (\`<agents-root>/spaces/<id>/\`). I coordinate workflows between the shared spaces root (where spaces are authored) and projects (where spaces are composed and used).

## Capabilities

### Space Authoring Workflows

I can help you author spaces:

1. **Authoring Guide**: Full multi-harness reference
   - Run \`/agent-spaces-manager:space-authoring\`

2. **Create Spaces**: Scaffold new spaces with proper structure
   - Run \`/agent-spaces-manager:create-space\` to get started

3. **Add Components**: Extend spaces with commands, skills, hooks, extensions
   - \`/agent-spaces-manager:add-command\` - Add a new command (Claude-only)
   - \`/agent-spaces-manager:add-skill\` - Add a new skill (shared)
   - \`/agent-spaces-manager:add-hook\` - Add lifecycle hooks (Claude or multi-harness)
   - \`/agent-spaces-manager:add-extension\` - Add an agent-harness (Pi) extension

4. **Validate**: Check for common issues before composing
   - \`/agent-spaces-manager:validate-space\` - Run lint and explain warnings

There is no publish step: shared spaces compose as \`space:<id>@dev\` straight from disk.

### Project Workflows

I can help you with project configuration:

1. **Configure Targets**: Set up which spaces to use
   - \`/agent-spaces-manager:update-project-targets\` - Edit asp-targets.toml

2. **Manage Dependencies**: Add/remove spaces from targets
   - \`asp add space:name@dev --target dev\`
   - \`asp remove space-name --target dev\`

3. **Validate Composition**: Check for issues
   - \`asp lint\` - Find warnings
   - \`asp explain <target>\` - See resolution details

4. **Select Harness** (Multi-Harness)
   - \`asp harnesses\` - List available harnesses (agent-harness, claude, codex, muse)
   - \`asp run <target> --harness <id>\` - Run with a specific harness
   - \`asp install --harness <id>\` - Materialize harness-specific output
   - \`asp build <target> --output <dir> --harness <id>\` - Build without launching

## Workflow Patterns

### Creating a New Space

1. "I want to create a new space for X"
2. I'll guide you through:
   - Choosing a space ID
   - Defining the purpose
   - Selecting initial components
   - Choosing harness support
   - Creating the structure

### Setting Up a Project

1. "I want to use spaces A, B, C in my project"
2. I'll assist with:
   - Creating asp-targets.toml
   - Configuring targets
   - Running install
   - Verifying the setup

## How I Work

I use the authoring guide and manager commands to guide you through workflows. When you describe what you want to accomplish, I'll:

1. **Understand your goal**: What are you trying to achieve?
2. **Suggest the approach**: Which commands/workflow to use
3. **Execute steps**: Run the appropriate commands
4. **Verify results**: Confirm everything worked

## Example Interactions

### "I want to create a space for frontend development"

I'll start by running \`/agent-spaces-manager:create-space\` and guide you through:
- Space ID suggestion: \`frontend-tools\`
- Description: What frontend capabilities to include
- Components: Commands for build, test, lint, etc.
- Skills: React patterns, TypeScript guidance, etc.
- Harness support: Claude-only, agent-harness-only, or multi-harness (agent-harness + claude + codex)

### "I need to add a code review command to my tools space"

I'll run \`/agent-spaces-manager:add-command\` with:
- Target space: Your tools space
- Command name: \`code-review\`
- Template: Best-practice command structure
- Validation: Ensure it integrates properly

### "How do my space edits reach my agents?"

There is nothing to publish. Shared spaces compose from disk as \`space:<id>@dev\`:
1. Edit the files under \`<agents-root>/spaces/<id>/\`
2. \`/agent-spaces-manager:validate-space\` to check for warnings
3. Re-run \`asp install\` (or \`asp run\`, which refreshes) in the consuming project
4. Commit the space in the agents repo to share it

## Context I Need

To help you effectively, tell me:

- **Where you're working**: The shared spaces root (\`<agents-root>/spaces/\`) or a project?
- **What you want to accomplish**: Create, modify, configure?
- **Which harnesses**: agent-harness, Claude, Codex, or multi-harness?
- **Any constraints**: Dependencies, team workflows?

## Available Commands

| Command | Purpose |
|---------|---------|
| \`/agent-spaces-manager:help\` | Show all available commands |
| \`/agent-spaces-manager:space-authoring\` | Full authoring guide |
| \`/agent-spaces-manager:create-space\` | Create a new space |
| \`/agent-spaces-manager:add-command\` | Add a command to a space (Claude-only) |
| \`/agent-spaces-manager:add-skill\` | Add a skill to a space (shared) |
| \`/agent-spaces-manager:add-hook\` | Add hooks to a space |
| \`/agent-spaces-manager:add-extension\` | Add an agent-harness (Pi) extension |
| \`/agent-spaces-manager:validate-space\` | Validate a space with lint |
| \`/agent-spaces-manager:update-project-targets\` | Configure project targets |

## Getting Started

If you're new to Agent Spaces, start with:
1. Run \`/agent-spaces-manager:help\` to see available commands
2. Read \`/agent-spaces-manager:space-authoring\` for the full guide
3. Tell me what you want to accomplish

Let's get started - what would you like to do?
`,
  },
  {
    path: 'commands/add-command.md',
    content: `# Add Command

Add a new command to an existing space with best-practice template.

## Usage

Run this command to add a command to a space. Commands are invokable actions that Claude can execute when the user requests them.

> Note: Commands are **Claude-only** (Codex maps them to prompts). For the agent-harness, use \`extensions/\` and register tools in TypeScript.

## Required Information

1. **Space ID or Path**: Which space to add the command to
2. **Command Name**: Filename for the command (kebab-case, without .md)
3. **Command Title**: Human-readable title
4. **Command Description**: What the command does

## Command Structure

Commands are stored as markdown files in the \`commands/\` directory:

\`\`\`
spaces/<space-id>/
└── commands/
    └── <command-name>.md
\`\`\`

When loaded, the command is accessible as:
- \`/agent-spaces-manager:<command-name>\` (fully-qualified)
- \`/<command-name>\` (if no collision with other plugins)

## Template

The created command will follow this structure:

\`\`\`markdown
# <Command Title>

<Brief description of what this command does>

## Usage

<When and how to use this command>

## Parameters

<Any inputs or context needed>

## Execution Steps

<What happens when this command runs>

## Example

<Show the command in action>

## Notes

<Important considerations or limitations>
\`\`\`

## Execution Steps

When you run this command, I will:

1. **Identify the target space**:
   - Ask which space to modify
   - Verify the space exists

2. **Get command details**:
   - Command name (kebab-case, e.g., \`run-tests\`)
   - Command title (e.g., "Run Tests")
   - Description of functionality

3. **Create the commands directory** (if needed):
   \`\`\`bash
   mkdir -p <agents-root>/spaces/<space-id>/commands
   \`\`\`

4. **Generate <command-name>.md** with best-practice template

5. **Verify** the command file is valid

## Example

Adding a "run-tests" command to a development space:

\`\`\`markdown
# Run Tests

Execute the project's test suite and report results.

## Usage

Run this command when you want to:
- Verify code changes don't break existing functionality
- Check test coverage
- Debug failing tests

## Parameters

- **Test Pattern** (optional): Glob pattern to filter tests (e.g., \`*.unit.test.ts\`)
- **Watch Mode** (optional): Whether to run in watch mode

## Execution Steps

1. Detect the test framework (Jest, Vitest, Bun test, etc.)
2. Run the appropriate test command
3. Parse and summarize results
4. Report failures with actionable suggestions

## Example

User: "Run the unit tests for the auth module"

I'll execute:
\\\`\\\`\\\`bash
bun test src/auth/**/*.test.ts
\\\`\\\`\\\`

## Notes

- Ensure dependencies are installed before running tests
- Some tests may require environment variables
- Watch mode is useful during active development
\`\`\`

## Best Practices for Commands

1. **Clear Purpose**: Each command should do one thing well
2. **Descriptive Names**: Use verb-noun format (e.g., \`run-tests\`, \`create-component\`)
3. **Document Parameters**: Be explicit about required vs optional inputs
4. **Show Examples**: Real usage examples help users understand the command
5. **Fully-Qualified References**: Always use \`/plugin:command\` format when referencing other commands

## Important Notes

- Commands are invoked via \`/plugin:command\` syntax
- Always use fully-qualified command names in your documentation
- Keep commands focused and composable
`,
  },
  {
    path: 'commands/add-extension.md',
    content: `# Add Extension

Add a new agent-harness (Pi) extension to an existing space with a best‑practice template.

## Usage

Run this command to add an extension. Extensions are TypeScript modules that register tools for the Pi-based \`agent-harness\`.

## Required Information

1. **Space ID or Path**: Which space to add the extension to
2. **Extension Name**: Filename for the extension (kebab-case, without .ts)
3. **Tool Name**: Tool identifier (kebab-case)
4. **Tool Description**: What the tool does

## Extension Structure

Extensions live in \`extensions/\`:

\`\`\`
spaces/<space-id>/
└── extensions/
    └── <extension-name>.ts
\`\`\`

## Template

The created extension will follow this structure:

\`\`\`ts
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'
import { Type } from 'typebox'

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "my_tool",
    label: "My Tool",
    description: "What this tool does",
    parameters: Type.Object({
      input: Type.String({ description: "Input string" })
    }),
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      return {
        content: [{ type: "text", text: \`Got: \${params.input}\` }],
        details: { success: true }
      }
    }
  })
}
\`\`\`

## Execution Steps

When you run this command, I will:

1. **Identify the target space**
2. **Collect extension details**
3. **Create the extensions directory** (if needed)
4. **Generate <extension-name>.ts** with the template
5. **Optionally update space.toml**:
   \`\`\`toml
   [pi]
   extensions = ["extensions/<extension-name>.ts"]
   \`\`\`

## Notes

- Extensions are for the **agent-harness** only. Claude and Codex ignore \`extensions/\`.
- If you use external deps, add \`extensions/package.json\` and list them.
- When bundling is enabled, ASP will bundle extensions to JS for execution.
- Configure bundling in \`space.toml\`:

\`\`\`toml
[pi.build]
bundle = true           # Bundle extensions to JS (default: true)
format = "esm"          # Output format: esm or cjs (default: esm)
target = "bun"          # Target runtime: bun or node (default: bun)
external = ["some-native-dep"]  # Dependencies to exclude from bundle
\`\`\`

## Best Practices

- Keep tools focused and composable
- Use clear, descriptive tool names
- Validate inputs and return helpful errors
- Prefer stable, deterministic outputs
`,
  },
  {
    path: 'commands/add-hook.md',
    content: `# Add Hook

Add a new hook to an existing space with proper configuration.

## Usage

Run this command to add a hook to a space. Hooks allow the harness to execute scripts at specific points during the session lifecycle.

## Required Information

1. **Space ID or Path**: Which space to add the hook to
2. **Hook Event**: When the hook should trigger
3. **Script Name**: Name of the script file
4. **Script Content**: What the script should do

## Hook Formats (Multi-Harness)

You can define hooks in two formats:

### 1) \`hooks/hooks.toml\` (Preferred for multi-harness)

Canonical, harness-agnostic format. ASP translates this to harness-specific formats.

**Supported events (canonical):**
- \`pre_tool_use\` - Before a tool executes
- \`post_tool_use\` - After a tool executes successfully
- \`post_tool_use_failure\` - After a tool fails
- \`session_start\` - When a session begins
- \`session_end\` - When a session ends
- \`stop\` - When the agent stops
- \`notification\` - On notifications
- \`user_prompt_submit\` - When user submits a prompt
- \`permission_request\` - On permission requests
- \`subagent_start\` - When a subagent starts
- \`subagent_stop\` - When a subagent stops
- \`pre_compact\` - Before context compaction

**Hook fields:**
- \`event\` (required) - The event name
- \`script\` (required) - Path to script relative to space root
- \`tools\` (optional) - Filter to specific tools, e.g., \`["Bash", "Write"]\`
- \`blocking\` (optional) - Whether hook blocks execution
- \`harness\` (optional) - Only run on specific harness, e.g., \`"claude"\`

Example:
\`\`\`toml
[[hook]]
event = "pre_tool_use"
script = "hooks/scripts/validate-tool.sh"
tools = ["Bash"]
blocking = true

[[hook]]
event = "session_start"
script = "hooks/scripts/setup.sh"

[[hook]]
event = "session_end"
script = "hooks/scripts/cleanup.sh"
harness = "claude"  # Only runs on Claude
\`\`\`

### 2) \`hooks/hooks.json\` (Claude-only)

Claude's native hook format. Use this when you only target Claude.

**Claude events:**
- \`PreToolUse\` - Before a tool executes
- \`PostToolUse\` - After a tool executes successfully
- \`PostToolUseFailure\` - After a tool fails
- \`SessionStart\` - When a session begins
- \`SessionEnd\` - When a session ends
- \`Stop\` - When the agent stops
- \`Notification\` - For notifications
- \`UserPromptSubmit\` - When user submits a prompt
- \`PermissionRequest\` - On permission requests
- \`SubagentStart\` - When a subagent starts
- \`SubagentStop\` - When a subagent stops
- \`PreCompact\` - Before context compaction

**Structure:** The \`hooks\` field must be an **object/record** (not an array) with event names as keys:

\`\`\`json
{
  "hooks": {
    "EventName": [
      {
        "matcher": "ToolPattern",
        "hooks": [
          {
            "type": "command",
            "command": "path/to/script"
          }
        ]
      }
    ]
  }
}
\`\`\`

**Key points:**
- \`matcher\` specifies which tools to match (e.g., \`"Bash"\`, \`"Write|Edit"\`, \`"*"\` for all)
- \`matcher\` is optional for events like \`Stop\` and \`UserPromptSubmit\` that don't use tool matching
- Each hook needs \`type: "command"\` and a \`command\` path

Example:
\`\`\`json
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "\${CLAUDE_PLUGIN_ROOT}/hooks/scripts/validate-bash.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "\${CLAUDE_PLUGIN_ROOT}/hooks/scripts/cleanup.sh"
          }
        ]
      }
    ]
  }
}
\`\`\`

**IMPORTANT**: Always use \`\${CLAUDE_PLUGIN_ROOT}\` for Claude hook paths.

## Event Mapping (hooks.toml → Claude)

| Canonical | Claude Event |
|-----------|--------------|
| \`pre_tool_use\` | \`PreToolUse\` |
| \`post_tool_use\` | \`PostToolUse\` |
| \`post_tool_use_failure\` | \`PostToolUseFailure\` |
| \`session_start\` | \`SessionStart\` |
| \`session_end\` | \`SessionEnd\` |
| \`stop\` | \`Stop\` |
| \`notification\` | \`Notification\` |
| \`user_prompt_submit\` | \`UserPromptSubmit\` |
| \`permission_request\` | \`PermissionRequest\` |
| \`subagent_start\` | \`SubagentStart\` |
| \`subagent_stop\` | \`SubagentStop\` |
| \`pre_compact\` | \`PreCompact\` |

## Hook Structure

\`\`\`
spaces/<space-id>/
└── hooks/
    ├── hooks.toml      # Multi-harness hook configuration (preferred)
    ├── hooks.json      # Claude hook configuration (optional)
    └── scripts/
        └── <script>.sh
\`\`\`

## Execution Steps

When you run this command, I will:

1. **Identify the target space**
2. **Confirm harness target** (Claude-only or multi-harness)
3. **Create the hooks structure** (if needed)
4. **Create or update hooks.toml or hooks.json**
5. **Create the script file** (with shebang and +x)
6. **Verify** the hook configuration is valid

## Example (Multi-Harness)

### hooks/hooks.toml
\`\`\`toml
[[hook]]
event = "pre_tool_use"
script = "hooks/scripts/log-tool.sh"
blocking = false
\`\`\`

### hooks/scripts/log-tool.sh
\`\`\`bash
#!/bin/bash
# Log tool use
# Always exits 0 - hooks should never fail

main() {
    echo "Tool: $ASP_TOOL_NAME"
    echo "Args: $ASP_TOOL_ARGS"
}

if ! main "$@"; then
    HOOK_LOG=~/praesidium/var/log/hooks-log.log
    mkdir -p "$(dirname "$HOOK_LOG")"
    echo "$(date -Iseconds) [FAIL] log-tool.sh: main returned non-zero" >> "$HOOK_LOG"
fi
exit 0
\`\`\`

## Example (Claude-only)

### hooks/hooks.json
\`\`\`json
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "\${CLAUDE_PLUGIN_ROOT}/hooks/scripts/log-tool.sh"
          }
        ]
      }
    ]
  }
}
\`\`\`

### hooks/scripts/log-tool.sh
\`\`\`bash
#!/bin/bash
# Log tool use
# Always exits 0 - hooks should never fail

main() {
    echo "Tool: $CLAUDE_TOOL_USE_NAME"
    echo "Input: $CLAUDE_TOOL_USE_INPUT"
}

if ! main "$@"; then
    HOOK_LOG=~/praesidium/var/log/hooks-log.log
    mkdir -p "$(dirname "$HOOK_LOG")"
    echo "$(date -Iseconds) [FAIL] log-tool.sh: main returned non-zero" >> "$HOOK_LOG"
fi
exit 0
\`\`\`

## Documentation Reference

For the latest Claude hooks documentation, see:
https://docs.anthropic.com/en/docs/claude-code/hooks

## Best Practices

1. **Prefer hooks.toml** for multi-harness spaces
2. **Use \`\${CLAUDE_PLUGIN_ROOT}\`** in Claude hooks.json paths
3. **Make Scripts Executable** (\`chmod +x\`)
4. **Keep Hooks Fast** (<5 seconds)
5. **Log for Debugging** (write to a log file, not stdout)
6. **Always Exit 0** - Hook scripts must never fail the agent. Use this pattern:

\`\`\`bash
#!/bin/bash
# Description of what this hook does
# Always exits 0 - hooks should never fail

main() {
    # Your hook logic here
    do_something || true
}

if ! main "$@"; then
    HOOK_LOG=~/praesidium/var/log/hooks-log.log
    mkdir -p "$(dirname "$HOOK_LOG")"
    echo "$(date -Iseconds) [FAIL] myscript.sh: main returned non-zero" >> "$HOOK_LOG"
fi
exit 0
\`\`\`

## Warnings

The lint system will emit warnings for:
- **W203**: Hook path missing \`\${CLAUDE_PLUGIN_ROOT}\` (Claude)
- **W204**: hooks/ exists but hooks.json missing or invalid (Claude)
- **W206**: Hook script not executable
`,
  },
  {
    path: 'commands/add-skill.md',
    content: `# Add Skill

Add a new skill to an existing space with best-practice template.

## Usage

Run this command to add a skill to a space. Skills are **shared across harnesses** (agent-harness, Claude and Codex), and follow the Agent Skills standard.

## Required Information

1. **Space ID or Path**: Which space to add the skill to
2. **Skill Name**: Name for the skill directory (kebab-case)
3. **Skill Title**: Human-readable title for the skill
4. **Skill Description**: What the skill does and when to use it

## Skill Structure

Skills are stored in \`skills/<skill-name>/SKILL.md\`:

\`\`\`
spaces/<space-id>/
└── skills/
    └── <skill-name>/
        └── SKILL.md
\`\`\`

## Template

The created SKILL.md will follow this structure. The \`name\`/\`description\` frontmatter is required (lint E208):

\`\`\`markdown
---
name: <skill-name>
description: <What this skill does and when to use it>
---

# <Skill Title>

<Description of what this skill does>

## When to Use

<Describe when the agent should activate this skill>

## Context

<Provide domain knowledge, best practices, patterns>

## Guidelines

<Specific instructions for how to apply this skill>

## Examples

<Show examples of the skill in action>
\`\`\`

## Execution Steps

When you run this command, I will:

1. **Identify the target space**:
   - Ask which space to modify
   - Verify the space exists

2. **Get skill details**:
   - Skill name (kebab-case, e.g., \`code-review\`)
   - Skill title (e.g., "Code Review Expert")
   - Description and trigger conditions

3. **Create the skill directory and file**:
   \`\`\`bash
   mkdir -p <agents-root>/spaces/<space-id>/skills/<skill-name>
   \`\`\`

4. **Generate SKILL.md** with best-practice template

5. **Verify** the skill is properly structured

## Example

Adding a TypeScript skill to a development space:

\`\`\`markdown
---
name: typescript-expert
description: Expert guidance for TypeScript development.
---

# TypeScript Expert

Expert guidance for TypeScript development.

## When to Use

Activate this skill when:
- Writing or reviewing TypeScript code
- Configuring tsconfig.json
- Debugging type errors
- Migrating JavaScript to TypeScript

## Context

TypeScript is a typed superset of JavaScript. Key principles:
- Prefer strict mode (\`"strict": true\`)
- Use explicit return types for public APIs
- Leverage type inference for local variables
- Avoid \`any\` - use \`unknown\` when type is truly unknown

## Guidelines

1. **Type Definitions**
   - Define interfaces for object shapes
   - Use type aliases for unions and complex types
   - Export types that are part of public API

2. **Generics**
   - Use meaningful constraint names
   - Default to simpler types when generics aren't needed

3. **Error Handling**
   - Type catch blocks properly
   - Use discriminated unions for result types

## Examples

### Good: Typed function
\\\`\\\`\\\`typescript
function processItems<T extends { id: string }>(items: T[]): Map<string, T> {
  return new Map(items.map(item => [item.id, item]));
}
\\\`\\\`\\\`
\`\`\`

## Best Practices

- Keep skills focused on a specific domain
- Provide concrete examples
- Include when-to-use triggers
- Document edge cases and gotchas
- Update skills as you learn new patterns
`,
  },
  {
    path: 'commands/create-space.md',
    content: `# Create Space

Scaffold a new space with the correct directory layout and initial files.

## Usage

Run this command to create a new space in the shared spaces root (\`<agents-root>/spaces/\`). You will be guided through the process.

## Required Information

1. **Space ID**: A kebab-case identifier (e.g., \`my-awesome-space\`)
   - Lowercase letters, numbers, and hyphens only
   - Must start with a letter
   - Maximum 64 characters

2. **Description**: Brief description of what this space does

3. **Initial Components** (optional):
   - Commands (Claude)
   - Skills (shared)
   - Hooks (Claude or multi-harness)
   - Extensions (agent-harness)

## Directory Structure (Multi-Harness Superset)

A space can target one or more harnesses. Start with the superset and omit what you don’t need:

\`\`\`
spaces/<space-id>/
├── space.toml              # Space manifest (required)
├── commands/               # Claude: slash commands (optional)
│   └── example.md
├── agents/                 # Claude: subagents (optional)
│   └── example.md
├── skills/                 # Shared: Agent Skills standard
│   └── example/
│       └── SKILL.md
├── hooks/                  # Hooks (Claude or multi-harness)
│   ├── hooks.toml          # Multi-harness hooks (preferred)
│   ├── hooks.json          # Claude-only hooks (optional)
│   └── scripts/
│       └── example.sh
├── mcp/                    # Claude: MCP server configs (optional)
│   └── mcp.json
├── extensions/             # agent-harness: TypeScript extensions (optional)
│   └── example.ts
├── scripts/                # Shared scripts (optional)
└── shared/                 # Shared assets (optional)
\`\`\`

### Claude-only Space (minimal)

\`\`\`
spaces/<space-id>/
├── space.toml
├── commands/
├── skills/
└── mcp/
\`\`\`

### agent-harness-only Space (minimal)

\`\`\`
spaces/<space-id>/
├── space.toml
├── extensions/
└── skills/
\`\`\`

## Execution Steps

When you run this command, I will:

1. **Ask for space details**:
   - Space ID (kebab-case identifier)
   - Description
   - Initial version for the manifest (default: 0.1.0)
   - Which components to include
   - Which harnesses to support

2. **Run the deterministic scaffold command**:
   \`\`\`bash
   asp repo new-space <space-id> --description "<description>" --version 0.1.0
   \`\`\`
   It writes \`space.toml\` and a README into \`<agents-root>/spaces/<space-id>/\` and validates the manifest.

3. **Add multi-harness fields to space.toml** if the space needs them:
   \`\`\`toml
   [harness]
   supports = ["agent-harness", "claude", "codex"]

   [claude]
   model = "sonnet"

   [pi]
   extensions = ["extensions/example.ts"]
   \`\`\`

4. **Create initial component files** based on your selections (only the directories you have content for)

5. **Verify the structure**: compose the space into a project target and run \`asp lint <target>\` (see \`/agent-spaces-manager:validate-space\`)

## Example

To create a space for frontend development tools:

1. Run \`/agent-spaces-manager:create-space\`
2. Enter ID: \`frontend-tools\`
3. Enter description: "Frontend development commands and skills"
4. Select components: commands, skills, hooks
5. I will run \`asp repo new-space frontend-tools --description "Frontend development commands and skills"\`
6. The space will be created at \`<agents-root>/spaces/frontend-tools/\` (see \`asp repo status\` for the resolved root)

## Next Steps After Creation

1. Add content to your commands/skills/agents/extensions
2. Validate: \`/agent-spaces-manager:validate-space\`
3. Test locally:
   - Claude: \`asp run <agents-root>/spaces/<space-id> --harness claude\`
   - Codex: \`asp run <agents-root>/spaces/<space-id> --harness codex\`
   - agent-harness runs need an agent target with a validated agent profile, not a bare space path
4. Compose it into a target: \`asp add space:<space-id>@dev --target <name>\`

There is no publish or version-bump step: the space is live as \`space:<space-id>@dev\` as soon as its files are on disk.

## Important Notes

- Space IDs must be unique within the shared spaces root
- The space.toml file is required and must pass validation
- Component directories (commands/, skills/, etc.) are only needed if you have content for them
- Use \`hooks/hooks.toml\` for multi-harness hooks; \`hooks/hooks.json\` is Claude-specific
- Always use \`\${CLAUDE_PLUGIN_ROOT}\` in Claude hook paths
`,
  },
  {
    path: 'commands/help.md',
    content: `# Help

Show available Agent Spaces CLI commands and management operations.

## Usage

Run this command when you need to see what \`asp\` commands are available or understand how to manage spaces.

## CLI Commands Reference

### Core Commands

| Command | Description |
|---------|-------------|
| \`asp run <target> [prompt]\` | Run a target, space reference, or path with optional prompt |
| \`asp install\` | Resolve targets, update asp-lock.json, and materialize project bundles under ASP_HOME |
| \`asp build <target> --output <dir>\` | Materialize plugins without launching the harness |

### Management Commands

| Command | Description |
|---------|-------------|
| \`asp add <spaceRef> --target <name>\` | Add a space reference to a target |
| \`asp remove <spaceId> --target <name>\` | Remove a space from a target |
| \`asp upgrade [spaceIds...] [--target <name>]\` | Update lock file pins according to selectors |
| \`asp diff [--target <name>]\` | Show pending lock changes without writing |

### Diagnostic Commands

| Command | Description |
|---------|-------------|
| \`asp explain [target]\` | Print resolved graph, pins, load order, warnings |
| \`asp describe [target]\` | Describe hooks, skills, tools, and lint warnings |
| \`asp lint [target]\` | Validate targets and detect conflicts |
| \`asp list\` | List targets, resolved spaces, and cached environments |
| \`asp doctor\` | Check harness binary, shared spaces root, cache permissions |
| \`asp harnesses\` | List available harnesses and their status |
| \`asp path <spaceId>\` | Print the filesystem path to a space |

### Shared Spaces Root Commands

Shared spaces live as plain directories under \`<agents-root>/spaces/<id>/\` and compose as \`space:<id>@dev\`. There is no registry to publish to; a space is live once its files are on disk.

| Command | Description |
|---------|-------------|
| \`asp repo init\` | Create the shared spaces dir and install this manager space |
| \`asp repo new-space <spaceId>\` | Scaffold a new space in the shared spaces root |
| \`asp repo status\` | Show the shared spaces root, its spaces, and uncommitted edits |
| \`asp spaces list\` | List spaces with their versions and descriptions |

### Other Commands

| Command | Description |
|---------|-------------|
| \`asp init\` | Create a new asp-targets.toml project file |
| \`asp gc\` | Garbage collect unreferenced store and cache entries |

## Key Command Options

### asp run

\`\`\`
asp run <target> [prompt]
  --harness <id>        Harness to use (default: agent-harness; also claude, codex, muse)
  --model <model>       Model override
  --yolo                Skip all permission prompts
  --dry-run             Print the harness command without executing
  --no-refresh          Skip refresh and use cached project bundles
  --debug               Enable Claude hook debugging
  --no-interactive      Run non-interactively
  --inherit-all         Inherit all harness settings
  --settings <file>     Path to settings JSON file or JSON string
\`\`\`

### asp install

\`\`\`
asp install
  --targets <names...>  Specific targets to install
  --harness <id>        Harness to use (default: agent-harness)
  --update              Update existing lock (re-resolve selectors)
  --refresh             Force re-copy from source (clear cache)
\`\`\`

## Available Harnesses

ASP supports multiple coding agent harnesses:

| Harness | Description |
|---------|-------------|
| \`agent-harness\` | Pi-based agent harness (default) - supports extensions, skills |
| \`claude\` | Claude Code - supports plugins, commands, agents, MCP, settings |
| \`codex\` | Codex - commands map to prompts, skills supported |
| \`muse\` | Muse harness |

Use \`asp harnesses\` to check which are available on your system.

## Harness Notes (Multi-Harness)

- Most commands accept \`--harness <id>\` (default: \`agent-harness\`) to select the runtime.
- The default \`agent-harness\` runs only agent targets with a validated agent profile; run dev targets, space refs and space paths with \`--harness claude\` or \`--harness codex\`.
- Project targets are harness-agnostic; choose the harness at run/build/install time.
- Project bundles are materialized per harness under ASP_HOME.

## Manager Space Commands

This space provides these commands for authoring workflows:

| Command | Description |
|---------|-------------|
| \`/agent-spaces-manager:help\` | Show this help |
| \`/agent-spaces-manager:space-authoring\` | Full authoring guide (multi-harness) |
| \`/agent-spaces-manager:create-space\` | Scaffold a new space with correct layout |
| \`/agent-spaces-manager:add-command\` | Add a command with template (Claude-only) |
| \`/agent-spaces-manager:add-skill\` | Add a skill with best-practice template |
| \`/agent-spaces-manager:add-hook\` | Add a hook with validation |
| \`/agent-spaces-manager:add-extension\` | Add an agent-harness (Pi) extension with template |
| \`/agent-spaces-manager:validate-space\` | Run lint checks and explain warnings |
| \`/agent-spaces-manager:update-project-targets\` | Help update project asp-targets.toml |

## Example Workflow

1. Create the shared spaces dir (once): \`asp repo init\`
2. Read the authoring guide: \`/agent-spaces-manager:space-authoring\`
3. Create a new space: \`/agent-spaces-manager:create-space\`
4. Add components (commands, skills, hooks, extensions)
5. Validate: \`/agent-spaces-manager:validate-space\`
6. Use in project: \`asp add space:my-space@dev --target dev\`
7. Run with a harness: \`asp run dev --harness claude\`
`,
  },
  {
    path: 'commands/space-authoring.md',
    content: `# Space Authoring Guide

Comprehensive guidance for creating and maintaining Agent Spaces, including multi‑harness layouts.

## Usage

Run this command when you need a complete reference for authoring spaces, including structure, manifests, hooks, extensions, composition, and troubleshooting.

## When to Use

Use this guide when:
- Creating a new space from scratch
- Adding components (commands, skills, agents, hooks, extensions)
- Structuring a space for maintainability
- Composing spaces into project targets
- Debugging space-related issues
- Adopting multi-harness layouts

## Core Concepts

### What is a Space?

A Space is a reusable capability module stored as a plain directory. Shared spaces live under the shared spaces root (\`<agents-root>/spaces/<id>/\`) and compose as \`space:<id>@dev\`; project and agent spaces live under \`<projectRoot>/spaces/\` and \`<agentRoot>/spaces/\`. A space materializes into harness-specific artifacts at runtime.

Key properties:
- **Live from disk**: Composition reads the space directory directly; there is no registry, tag or publish step
- **Composable**: Multiple spaces combine into run targets
- **Self-contained**: Each space is an independent capability module

### Multi-Harness Layout (agent-harness vs Claude)

The canonical harnesses are \`agent-harness\` (Pi-based, the default), \`claude\`, \`codex\` and \`muse\`.

| Component | agent-harness | Claude | Notes |
|-----------|---------------|--------|-------|
| \`commands/\` | ❌ | ✅ | Claude slash commands (Codex maps them to prompts) |
| \`agents/\` | ❌ | ✅ | Claude subagents only |
| \`skills/\` | ✅ | ✅ | Shared Agent Skills standard |
| \`hooks/hooks.toml\` | ✅ (bridge) | ✅ (translated) | Preferred multi-harness format |
| \`hooks/hooks.json\` | ❌ | ✅ | Claude-only format |
| \`mcp/\` | ❌ | ✅ | Claude MCP servers |
| \`extensions/\` | ✅ | ❌ | agent-harness tools (TypeScript) |

### Space Structure (Multi-Harness Superset)

\`\`\`
spaces/<space-id>/
├── space.toml              # Manifest (required)
├── commands/               # Claude: slash commands
├── agents/                 # Claude: subagents
├── skills/                 # Shared skills (Agent Skills standard)
├── hooks/                  # Hook configs + scripts
│   ├── hooks.toml          # Multi-harness hooks (preferred)
│   ├── hooks.json          # Claude-only hooks (optional)
│   └── scripts/
├── mcp/                    # Claude: MCP servers
├── extensions/             # agent-harness: TypeScript extensions
├── scripts/                # Shared scripts
└── shared/                 # Shared assets
\`\`\`

**Claude-only spaces** can omit \`extensions/\` and \`[pi]\`.
**agent-harness-only spaces** can omit \`commands/\`, \`agents/\`, and \`mcp/\`.

### space.toml Manifest

Required fields:
\`\`\`toml
schema = 1
id = "my-space"          # Kebab-case identifier
\`\`\`

Optional fields (common):
\`\`\`toml
version = "1.0.0"        # Manifest version (informational; nothing resolves by it)
description = "..."      # What this space does

[plugin]
name = "my-space"        # Claude plugin name override
version = "1.0.0"        # Claude plugin version override
description = "..."      # Plugin description override
license = "MIT"          # License identifier
keywords = ["tools"]     # Keywords for discovery
homepage = "https://..."  # Homepage URL
repository = "https://..." # Repository URL

[plugin.author]
name = "Author Name"
email = "author@example.com"
url = "https://..."
\`\`\`

Settings fields (Claude):
\`\`\`toml
[settings]
model = "sonnet"          # use model aliases, not pinned versions

[settings.permissions]
allow = ["Bash(npm test:*)"]
deny = ["Bash(rm -rf:*)"]

[settings.env]
NODE_ENV = "development"
\`\`\`

Multi-harness fields:
\`\`\`toml
[harness]
supports = ["agent-harness", "claude", "codex"]

[claude]
model = "sonnet"
mcp = ["mcp/custom.json"]  # explicit MCP config paths

[pi]                       # agent-harness settings
extensions = ["extensions/example.ts"]

[pi.build]
bundle = true
format = "esm"
target = "bun"
external = ["some-native-dep"]
\`\`\`

Dependencies:
\`\`\`toml
[deps]
spaces = ["space:base-tools@dev"]
\`\`\`

### Multi-Harness Minimal Example

\`\`\`
my-space/
├── space.toml
├── commands/
│   └── build.md
├── extensions/
│   └── lint.ts
└── skills/
    └── code-review/
        └── SKILL.md
\`\`\`

\`\`\`toml
schema = 1
id = "my-space"
version = "0.1.0"

[plugin]
name = "my-space"

[harness]
supports = ["agent-harness", "claude"]

[pi]
extensions = ["extensions/lint.ts"]
\`\`\`

## Guidelines

### Naming Conventions

1. **Space IDs**: kebab-case, lowercase
   - Good: \`frontend-tools\`, \`code-review\`, \`api-testing\`
   - Bad: \`FrontendTools\`, \`code_review\`, \`API-Testing\`

2. **Commands** (Claude): verb-noun or descriptive kebab-case
   - Good: \`run-tests\`, \`create-component\`, \`analyze-code\`
   - Bad: \`tests\`, \`RunTests\`, \`component_creator\`

3. **Skills** (shared): domain-focused kebab-case
   - Good: \`typescript-expert\`, \`react-patterns\`, \`api-design\`

### Component Guidelines

**Commands (Claude)**:
- One clear purpose per command
- Document parameters and examples
- Use fully-qualified references: \`/plugin:command\`
- Include execution steps

**Skills (shared)**:
- Focus on domain expertise
- Include "when to use" triggers
- Provide concrete examples
- Document best practices and gotchas

**Hooks**:
- **Reference**: Always consult https://docs.anthropic.com/en/docs/claude-code/hooks for the latest hooks documentation
- Prefer \`hooks/hooks.toml\` for multi-harness (harness-agnostic format)
- Use \`\${CLAUDE_PLUGIN_ROOT}\` in Claude hooks.json paths
- Keep scripts fast (<5 seconds)
- Handle errors gracefully (exit 0) - hooks should never fail
- Make scripts executable
- **hooks.toml abstract events**: \`pre_tool_use\`, \`post_tool_use\`, \`post_tool_use_failure\`, \`session_start\`, \`session_end\`, \`stop\`, \`notification\`, \`user_prompt_submit\`, \`permission_request\`, \`subagent_start\`, \`subagent_stop\`, \`pre_compact\`
- **Claude events**: \`PreToolUse\`, \`PostToolUse\`, \`PostToolUseFailure\`, \`SessionStart\`, \`SessionEnd\`, \`Stop\`, \`Notification\`, \`UserPromptSubmit\`, \`PermissionRequest\`, \`SubagentStart\`, \`SubagentStop\`, \`PreCompact\`

**Extensions (agent-harness)**:
- Use TypeScript modules that register tools
- Keep dependencies explicit
- Prefer small, composable tools

### Change Workflow

There is no publish, tag or version-bump step. A shared space is live as \`space:<id>@dev\` as soon as its files are on disk:

1. Make changes to space content under \`<agents-root>/spaces/<id>/\`
2. Validate: \`/agent-spaces-manager:validate-space\`
3. Re-run \`asp install\` (or \`asp run\`, which refreshes) in consuming projects
4. Commit the change in the agents repo so other checkouts get it

Every consumer sees an edit on its next install, so treat removing commands/skills or changing their behavior as a breaking change for every target that composes the space.

## Common Patterns

### Layered Spaces

Base space with core functionality, specialized spaces depend on it:

\`\`\`
base-tools/          # Shared utilities
├── space.toml
└── commands/
    └── common.md

frontend-tools/      # Depends on base
├── space.toml       # deps.spaces = ["space:base-tools@dev"]
└── commands/
    └── build-ui.md
\`\`\`

### Feature Toggles via Composition

Instead of configuring features, compose different spaces:

\`\`\`toml
# asp-targets.toml
[targets.minimal]
compose = ["space:core@dev"]

[targets.full]
compose = [
  "space:core@dev",
  "space:advanced-features@dev"
]
\`\`\`

### Multi-Harness Run

Targets are harness-agnostic. Choose a harness at runtime:

\`\`\`bash
asp run dev --harness claude
asp run dev --harness codex
\`\`\`

The default \`agent-harness\` runs only agent targets with a validated agent profile; run dev targets, space refs and space paths with \`--harness claude\` or \`--harness codex\`.

Use \`asp harnesses\` to check which harnesses are available on your system.

## Troubleshooting

### Common Issues

1. **Space manifest not found**
   - Verify space ID matches the directory name exactly
   - Check \`<agents-root>/spaces/<id>/space.toml\` exists (\`asp repo status\` shows the resolved root)
   - For \`space:project:<id>\`, check \`<projectRoot>/spaces/<id>/space.toml\`

2. **Install fails on a selector**
   - \`@stable\`, dist-tags, semver ranges and \`git:\` pins are retired
   - Use \`space:<id>@dev\` or bare \`space:<id>\`

3. **Hooks not running**
   - Check hooks.toml or hooks.json syntax
   - Verify scripts are executable
   - Check for \`\${CLAUDE_PLUGIN_ROOT}\` in paths
   - Look for W203, W204, W206 warnings

4. **Command collisions**
   - Use fully-qualified names: \`/plugin:command\`
   - Rename conflicting commands
   - Consider if spaces should be combined

### Validation Commands

\`\`\`bash
# Lint a target that composes the space (lint takes a target, not a path)
asp lint <target>

# Explain resolution
asp explain <target>

# Check plugin structure (prints the materialized plugin directories)
asp build <target> --output ./debug-plugins --harness claude
\`\`\`

## Best Practices

1. **Single Responsibility**: Each space should have a focused purpose
2. **Document Everything**: Commands, skills, and agents need clear docs
3. **Test Locally First**: Use \`asp run <path> --harness claude\` (or \`codex\`) before composing a space into shared targets
4. **Change Carefully**: Edits are live for every consumer on its next install
5. **Minimize Dependencies**: Only depend on what you need
6. **Fully-Qualified References**: Always use \`/plugin:command\` format
`,
  },
  {
    path: 'commands/update-project-targets.md',
    content: `# Update Project Targets

Help update a project's \`asp-targets.toml\` to compose spaces into run targets.

## Usage

Run this command when you need to configure which spaces are used in a project's targets.

## What is asp-targets.toml?

The \`asp-targets.toml\` file in a project root defines run targets - named compositions of spaces that can be launched with \`asp run <target>\`.

## File Location

\`\`\`
project-root/
├── asp-targets.toml    # Defines targets
├── asp-lock.json       # Generated lock file (don't edit manually)
├── spaces/             # Optional project-local spaces (space:project:<id>)
│   └── my-tools/
│       └── space.toml
└── ...
\`\`\`

## File Format

\`\`\`toml
schema = 2

[targets.dev]
description = "Development environment with all tools"
compose = [
  "space:defaults@dev",
  "space:praesidium-defaults",
  "space:project:my-tools"
]

[targets.review]
description = "Code review focused environment"
compose = ["space:defaults@dev"]

# Per-target birth defaults (optional)
[targets.review.provisioning]
harness = "claude"

# Claude options for this target (optional)
[targets.review.provisioning.claude]
model = "sonnet"
permission_mode = "plan"
\`\`\`

\`schema = 2\` is the only accepted schema. Use model aliases (\`opus\`, \`sonnet\`, \`haiku\`) rather than pinned model versions.

## Space Reference Formats

| Format | Example | Description |
|--------|---------|-------------|
| Dev | \`space:defaults@dev\` | The space's current files on disk |
| Bare | \`space:defaults\` | Same as \`@dev\` |
| Project-local | \`space:project:my-tools\` | \`<projectRoot>/spaces/my-tools/\` |
| Agent-local | \`space:agent:muse-meta\` | \`<agentRoot>/spaces/muse-meta/\`; valid in an agent's \`agent-profile.toml\` \`[spaces]\` lists, not in \`asp-targets.toml\` |

Shared spaces resolve from the spaces directory on disk. There is no registry to publish to: \`@stable\`, dist-tags, semver ranges and \`git:\` pins were retired; they no longer resolve and \`asp install\` fails on them.

## Harness Notes (Multi-Harness)

- Targets are **harness-agnostic**. You select the harness at runtime:
  - \`asp run dev --harness claude\`
  - \`asp run dev --harness codex\`
  - The default \`agent-harness\` runs only agent targets with a validated agent profile; run dev targets, space refs and space paths with \`--harness claude\` or \`--harness codex\`.
- You can also materialize per harness:
  - \`asp install --harness claude\`
  - \`asp build dev --output ./out --harness agent-harness\`
- A target can set its birth default with \`[targets.<name>.provisioning] harness = "<id>"\`.
- Use \`asp harnesses\` to list available harnesses on your system.

## Execution Steps

When you run this command, I will:

1. **Locate or create asp-targets.toml**:
   - Check if file exists in project root
   - Create with \`schema = 2\` and a \`[targets.<name>]\` table if missing

2. **Understand your needs**:
   - Which target to modify (or create new)
   - Which spaces to add/remove
   - Any provisioning or Claude options to configure

3. **Update the file**:
   - Add/remove space references with \`asp add\` / \`asp remove\`
   - Edit \`[targets.<name>.provisioning.claude]\` for Claude options
   - Validate with \`asp lint\`

4. **Regenerate lock file**:
   \`\`\`bash
   asp install
   \`\`\`

5. **Show the changes** for review

## Example Workflows

### Adding a space to a target
\`\`\`bash
asp add space:praesidium-defaults --target dev
\`\`\`
\`\`\`toml
# Before
[targets.dev]
compose = ["space:defaults@dev"]

# After
[targets.dev]
compose = ["space:defaults@dev", "space:praesidium-defaults"]
\`\`\`

### Creating a new target
\`\`\`toml
[targets.new-target]
description = "Description of this target"
compose = [
  "space:defaults@dev",
  "space:project:my-tools"
]
\`\`\`

### Removing a space
\`\`\`bash
asp remove praesidium-defaults --target dev
\`\`\`
\`\`\`toml
# Before
[targets.dev]
compose = ["space:defaults@dev", "space:praesidium-defaults"]

# After
[targets.dev]
compose = ["space:defaults@dev"]
\`\`\`

## CLI Shortcuts

\`--target\` is required for \`asp add\` and \`asp remove\`. Both run \`asp install\` afterwards unless you pass \`--no-install\`.

\`\`\`bash
# Add a space to a target
asp add space:my-space --target dev

# Remove a space from a target (bare id or the full ref as written)
asp remove my-space --target dev
asp remove space:project:my-tools --target dev

# See what would change
asp diff --target dev
\`\`\`

## After Updating

1. **Install to update lock file**:
   \`\`\`bash
   asp install                 # all targets
   asp install --targets dev   # specific targets
   \`\`\`

2. **Verify the resolution**:
   \`\`\`bash
   asp explain dev
   \`\`\`

3. **Run the target**:
   \`\`\`bash
   asp run dev --harness claude
   \`\`\`

## Best Practices

1. **Compose live spaces**: write \`space:<id>@dev\` or bare \`space:<id>\`
2. **Keep project-specific spaces local**: put them under \`spaces/\` and reference them as \`space:project:<id>\`
3. **Group related spaces**: Create focused targets (dev, review, deploy)
4. **Document targets**: Use the \`description\` field
5. **Commit asp-targets.toml**: This is your source of truth
6. **Commit asp-lock.json**: This ensures reproducibility

## Troubleshooting

- **Space manifest not found**: Check that \`spaces/<id>/space.toml\` exists in the shared spaces directory (or in the project's \`spaces/\` for \`space:project:<id>\`)
- **Not a valid space reference**: Use one of the formats above; \`space:agent:<id>\` belongs in \`agent-profile.toml\`
- **Install fails on \`@stable\`, a semver range or \`git:<sha>\`**: Those selectors are retired; replace them with \`@dev\` or drop the selector
- **Lint warnings**: Run \`asp lint\` to see composition issues
`,
  },
  {
    path: 'commands/validate-space.md',
    content: `# Validate Space

Run lint checks against a space to catch common issues before composing it into a target.

## Usage

Run this command any time you want to verify a space is well‑formed and compatible.

## What It Does

- Runs \`asp lint\` against a project target that composes the space (lint takes a target, not a space path)
- Surfaces warnings like command collisions, invalid hooks, and plugin structure issues
- Helps ensure multi‑harness artifacts are present when needed

## Execution Steps

When you run this command, I will:

1. **Identify the space and a project target that composes it** (add one with \`asp add space:<space-id>@dev --target <name>\` if needed)
2. **Run lint** from the project:
   \`\`\`bash
   asp lint <target>
   asp describe <target> --harness claude   # hooks, skills, tools and lint warnings per harness
   \`\`\`
3. **Explain warnings** and how to fix them

## Warning Codes

| Code | Name | Description |
|------|------|-------------|
| **W201** | Command collision | Same command name defined in multiple spaces |
| **W202** | Agent command namespace | Agent references unqualified \`/command\` instead of \`/plugin:command\` |
| **W203** | Hook path missing root | Claude hook path missing \`\${CLAUDE_PLUGIN_ROOT}\` prefix |
| **W204** | Invalid hooks config | hooks/ directory exists but hooks.toml/hooks.json missing or invalid |
| **W205** | Plugin name collision | Multiple spaces with the same plugin name |
| **W206** | Non-executable script | Hook script is not executable (\`chmod +x\` needed) |
| **W207** | Invalid plugin structure | Plugin directory structure is invalid |
| **E208** | SKILL.md missing frontmatter | A skill's SKILL.md lacks \`name\`/\`description\` frontmatter |

## Tips

- Fix warnings before composing the space (shared spaces are live as soon as they are on disk)
- Use fully-qualified commands in docs (\`/plugin:command\`)
- Prefer \`hooks/hooks.toml\` for multi-harness hooks
- Run \`asp explain <target>\` for detailed resolution info
`,
  },
  {
    path: 'hooks/hooks.json',
    content: `{
  "description": "Agent Spaces Manager startup hook",
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup",
        "hooks": [
          {
            "type": "command",
            "command": "\${CLAUDE_PLUGIN_ROOT}/hooks/scripts/startup.sh"
          }
        ]
      }
    ]
  }
}
`,
  },
  {
    path: 'hooks/scripts/startup.sh',
    executable: true,
    content: `#!/bin/bash
# ASP startup info
# Always exits 0 - hooks should never fail

main() {
    asp --help
}

if ! main "$@"; then
    HOOK_LOG=~/praesidium/var/log/hooks-log.log
    mkdir -p "$(dirname "$HOOK_LOG")"
    echo "$(date -Iseconds) [FAIL] startup.sh: main returned non-zero" >> "$HOOK_LOG"
fi
exit 0
`,
  },
  {
    path: 'space.toml',
    content: `# Agent Spaces Manager
# Built-in management space for creating and managing spaces in the shared spaces root

schema = 1
id = "agent-spaces-manager"
version = "1.0.0"
description = "Management space for creating and managing Agent Spaces"

[plugin]
name = "agent-spaces-manager"
description = "Tools and guidance for authoring and managing Agent Spaces"
license = "MIT"
keywords = ["management", "authoring", "scaffolding"]

`,
  },
]
