/**
 * CLI red/green tests for Phase 4 context-template behavior (T-01045).
 *
 * Spec sources:
 * - PROMPT_TEMPLATE_UPDATES.md sections "Update `asp run --dry-run`",
 *   "`asp resolve-reminder`", and "E2E manual validation (NO MOCKS)"
 * - agentchat DM #133 from animata@agent-spaces to smokey@agent-spaces
 * - agentchat DM #137 from larry@agent-spaces to smokey@agent-spaces
 *
 * These tests use real temp directories and invoke the actual `asp` CLI so
 * future sessions can reproduce the same red/green behavior without mocks.
 */

import { afterEach, describe, expect, test } from 'bun:test'
import { execFileSync } from 'node:child_process'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { getProjectHarnessOutputPath } from 'spaces-config'

const ASP_CLI = join(import.meta.dirname, '..', '..', 'bin', 'asp.js')
const CODEX_SHIM_DIR = join(process.cwd(), 'integration-tests', 'fixtures', 'codex-shim')

const tempDirs: string[] = []

afterEach(async () => {
  await Promise.all(tempDirs.map((path) => rm(path, { recursive: true, force: true })))
  tempDirs.length = 0
})

function runAsp(
  args: string[],
  options: { cwd?: string; env?: Record<string, string> } = {}
): { stdout: string; stderr: string; exitCode: number } {
  try {
    const stdout = execFileSync('bun', ['run', ASP_CLI, ...args], {
      cwd: options.cwd,
      encoding: 'utf8',
      timeout: 15000,
      env: { ...process.env, ...options.env, NO_COLOR: '1' },
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    return { stdout, stderr: '', exitCode: 0 }
  } catch (error: any) {
    return {
      stdout: error.stdout?.toString() ?? '',
      stderr: error.stderr?.toString() ?? '',
      exitCode: error.status ?? 1,
    }
  }
}

async function createTempDir(prefix: string): Promise<string> {
  const path = await mkdtemp(join(tmpdir(), prefix))
  tempDirs.push(path)
  return path
}

async function setupCliFixture() {
  const aspHome = await createTempDir('asp-phase4-home-')
  const projectDir = await createTempDir('asp-phase4-project-')
  const agentsRoot = await createTempDir('asp-phase4-agents-')
  const targetName = 'smokey-target'
  const agentRoot = join(agentsRoot, targetName)

  await mkdir(agentRoot, { recursive: true })
  await writeFile(
    join(agentRoot, 'agent-profile.toml'),
    `
schemaVersion = 2

[identity]
display = "Smokey"
`.trimStart()
  )

  await writeFile(
    join(projectDir, 'asp-targets.toml'),
    `
schema = 1

[targets.${targetName}]
compose = ["space:test@stable"]

[targets.${targetName}.codex]
model = "gpt-5.5"
`.trimStart()
  )

  const codexHome = join(
    getProjectHarnessOutputPath(projectDir, targetName, 'codex', aspHome),
    'codex.home'
  )
  await mkdir(join(codexHome, 'skills'), { recursive: true })
  await mkdir(join(codexHome, 'prompts'), { recursive: true })
  await writeFile(
    join(codexHome, 'config.toml'),
    'model = "gpt-5.5"\napproval_policy = "never"\nsandbox_mode = "danger-full-access"\n'
  )
  await writeFile(join(codexHome, 'AGENTS.md'), '<!-- Generated by agent-spaces. -->\n')
  await writeFile(
    join(codexHome, 'manifest.json'),
    JSON.stringify({
      schemaVersion: 1,
      harnessId: 'codex',
      targetName,
      generatedAt: new Date().toISOString(),
      spaces: [],
      skills: [],
      prompts: [],
      mcpServers: [],
      instructions: [],
    })
  )

  await writeFile(
    join(projectDir, 'asp-lock.json'),
    JSON.stringify({
      lockfileVersion: 1,
      resolverVersion: 1,
      generatedAt: new Date().toISOString(),
      registry: { type: 'git', url: '/tmp/fake-registry' },
      spaces: {},
      targets: {
        [targetName]: {
          compose: ['space:test@stable'],
          roots: [],
          loadOrder: [],
          envHash: 'sha256:0000000000000000000000000000000000000000000000000000000000000000',
          harnesses: {
            codex: {
              envHash: 'sha256:0000000000000000000000000000000000000000000000000000000000000000',
            },
          },
        },
      },
    })
  )

  const env = {
    ASP_AGENTS_ROOT: agentsRoot,
    PATH: `${CODEX_SHIM_DIR}:${process.env.PATH ?? ''}`,
  }

  return {
    aspHome,
    projectDir,
    agentsRoot,
    agentRoot,
    targetName,
    env,
  }
}

describe('asp resolve-reminder (T-01045)', () => {
  test('outputs only reminder sections from a v2 context template', async () => {
    const fixture = await setupCliFixture()
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "append"

[[prompt]]
name = "prompt-alpha"
type = "inline"
content = "prompt body should stay out of reminder output"

[[reminder]]
name = "reminder-alpha"
type = "inline"
content = "reminder body only"

[[reminder]]
name = "reminder-beta"
type = "inline"
content = "second reminder"
`.trimStart()
    )

    const result = runAsp(
      [
        'resolve-reminder',
        fixture.targetName,
        '--agents-root',
        fixture.agentsRoot,
        '--asp-home',
        fixture.aspHome,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('reminder body only')
    expect(result.stdout).toContain('second reminder')
    expect(result.stdout).not.toContain('prompt body should stay out of reminder output')
  })

  test('infers the active target from hook runtime env for bare resolve-reminder', async () => {
    const fixture = await setupCliFixture()
    const bundleRoot = getProjectHarnessOutputPath(
      fixture.projectDir,
      fixture.targetName,
      'claude',
      fixture.aspHome
    )
    const pluginRoot = join(bundleRoot, 'plugins', 'praesidium-defaults')
    await mkdir(pluginRoot, { recursive: true })
    await writeFile(join(fixture.agentRoot, 'session-note.md'), 'agent session note')
    await writeFile(
      join(fixture.agentRoot, 'agent-profile.toml'),
      `
schemaVersion = 2

[session]
additionalContext = ["agent-root:///session-note.md"]
`.trimStart()
    )
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "append"

[[prompt]]
name = "required-prompt"
type = "file"
path = "agent-root:///missing-prompt.md"
required = true

[[reminder]]
name = "session-context"
type = "slot"
source = "session.additionalContext"
`.trimStart()
    )

    const result = runAsp(
      ['resolve-reminder', '--agents-root', fixture.agentsRoot, '--asp-home', fixture.aspHome],
      {
        cwd: fixture.projectDir,
        env: {
          ...fixture.env,
          CLAUDE_PLUGIN_ROOT: pluginRoot,
        },
      }
    )

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('agent session note')
    expect(result.stdout).not.toContain('missing-prompt')
  })

  test('fails for legacy v1 templates', async () => {
    const fixture = await setupCliFixture()
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 1
mode = "replace"

[[section]]
name = "legacy-prompt"
type = "inline"
content = "legacy prompt body"
`.trimStart()
    )

    const result = runAsp(
      [
        'resolve-reminder',
        fixture.targetName,
        '--agents-root',
        fixture.agentsRoot,
        '--asp-home',
        fixture.aspHome,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    expect(result.exitCode).toBe(1)
    expect(result.stderr).toContain('schema_version')
  })
})

describe('asp run --dry-run context-template visibility (T-01045)', () => {
  test('shows separate prompt and reminder sections with per-section char counts', async () => {
    const fixture = await setupCliFixture()
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "append"
max_chars = 200

[[prompt]]
name = "prompt-alpha"
type = "inline"
content = "prompt alpha"

[[prompt]]
name = "prompt-beta"
type = "inline"
content = "prompt beta"

[[reminder]]
name = "reminder-alpha"
type = "inline"
content = "reminder alpha"
`.trimStart()
    )

    const result = runAsp(
      [
        'run',
        fixture.targetName,
        '--harness',
        'codex',
        '--dry-run',
        '--no-refresh',
        '--asp-home',
        fixture.aspHome,
        '--project',
        fixture.projectDir,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    const combined = result.stdout + result.stderr
    expect(result.exitCode).toBe(0)
    expect(combined).toContain('System Prompt')
    expect(combined).toContain('Session Reminder')
    expect(combined).toContain('prompt alpha')
    expect(combined).toContain('reminder alpha')
    expect(combined).toMatch(/prompt-alpha=\d+/)
    expect(combined).toMatch(/prompt-beta=\d+/)
    expect(combined).toMatch(/reminder-alpha=\d+/)
    expect(combined).toContain('Budget:')
  })

  test('interpolates agent_name inside file prompt sections in dry-run output', async () => {
    const fixture = await setupCliFixture()
    await writeFile(join(fixture.agentsRoot, 'AGENT_MOTD.md'), 'Hello {{agent_name}} from MOTD.')
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "replace"

[[prompt]]
name = "platform"
type = "file"
path = "AGENT_MOTD.md"
`.trimStart()
    )

    const result = runAsp(
      [
        'run',
        fixture.targetName,
        '--harness',
        'codex',
        '--dry-run',
        '--no-refresh',
        '--asp-home',
        fixture.aspHome,
        '--project',
        fixture.projectDir,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    const combined = result.stdout + result.stderr
    expect(result.exitCode).toBe(0)
    expect(combined).toContain(`Hello ${fixture.targetName} from MOTD.`)
    expect(combined).not.toContain('{{agent_name}}')
  })

  test('surfaces max_chars failures with per-section size details', async () => {
    const fixture = await setupCliFixture()
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "replace"
max_chars = 20

[[prompt]]
name = "prompt-alpha"
type = "inline"
content = "12345678901"

[[reminder]]
name = "reminder-alpha"
type = "inline"
content = "abcdefghijk"
`.trimStart()
    )

    const result = runAsp(
      [
        'run',
        fixture.targetName,
        '--harness',
        'codex',
        '--dry-run',
        '--no-refresh',
        '--asp-home',
        fixture.aspHome,
        '--project',
        fixture.projectDir,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    const combined = result.stdout + result.stderr
    expect(result.exitCode).toBe(1)
    expect(combined).toContain('max_chars 20')
    expect(combined).toContain('Section sizes:')
    expect(combined).toContain('prompt-alpha=11')
    expect(combined).toContain('reminder-alpha=11')
  })

  test('supports [session] reminder config from a real agent-profile.toml in dry-run flow', async () => {
    const fixture = await setupCliFixture()
    await writeFile(
      join(fixture.agentRoot, 'agent-profile.toml'),
      `
schemaVersion = 2

[identity]
display = "Smokey"

[session]
additionalContext = ["session-banner.md"]
additionalExec = ["printf 'task context'"]
`.trimStart()
    )
    await writeFile(join(fixture.agentsRoot, 'session-banner.md'), 'Session banner')
    await writeFile(
      join(fixture.agentsRoot, 'context-template.toml'),
      `
schema_version = 2
mode = "append"

[[prompt]]
name = "prompt-alpha"
type = "inline"
content = "prompt alpha"

[[reminder]]
name = "session-context"
type = "slot"
source = "session.additionalContext"

[[reminder]]
name = "session-exec"
type = "slot"
source = "session.additionalExec"
`.trimStart()
    )

    const result = runAsp(
      [
        'run',
        fixture.targetName,
        '--harness',
        'codex',
        '--dry-run',
        '--no-refresh',
        '--asp-home',
        fixture.aspHome,
        '--project',
        fixture.projectDir,
      ],
      { cwd: fixture.projectDir, env: fixture.env }
    )

    const combined = result.stdout + result.stderr
    expect(result.exitCode).toBe(0)
    expect(combined).toContain('Session Reminder')
    expect(combined).toContain('Session banner')
    expect(combined).toContain('task context')
    expect(combined).not.toContain('unknown property "session"')
  })
})
