/**
 * RED tests: CLI --model-reasoning-effort flag for asp run (T-00947)
 *
 * WHY: The `asp run` command must expose --model-reasoning-effort as a CLI option
 * so users can override Codex reasoning effort at invocation time. The dry-run
 * output (--print-command) must include `-c model_reasoning_effort="<value>"`.
 *
 * PASS CONDITIONS (all tests green when):
 * 1. `asp run --help` lists `--model-reasoning-effort` as a recognized option
 * 2. `asp run <target> --harness codex --model-reasoning-effort high --print-command`
 *    emits a command string containing `model_reasoning_effort="high"`
 * 3. An unknown `--model-reasoning-effort` option does NOT cause "unknown option" error
 *    (i.e., commander registers the flag)
 *
 * wrkq task: T-00947
 */

import { describe, expect, test } from 'bun:test'
import { execFileSync } from 'node:child_process'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const ASP_CLI = join(import.meta.dirname, '..', '..', 'bin', 'asp.js')

function runAsp(
  args: string[],
  options: { env?: Record<string, string> } = {}
): { stdout: string; stderr: string; exitCode: number } {
  try {
    const result = execFileSync('bun', ['run', ASP_CLI, ...args], {
      encoding: 'utf8',
      timeout: 15000,
      env: { ...process.env, ...options.env, NO_COLOR: '1' },
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    return { stdout: result, stderr: '', exitCode: 0 }
  } catch (err: any) {
    return {
      stdout: err.stdout?.toString() ?? '',
      stderr: err.stderr?.toString() ?? '',
      exitCode: err.status ?? 1,
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. --help shows the flag
// ─────────────────────────────────────────────────────────────────────────────

describe('asp run --help: --model-reasoning-effort (T-00947)', () => {
  test('help output lists --model-reasoning-effort option', () => {
    const { stdout, stderr } = runAsp(['run', '--help'])
    const combined = stdout + stderr
    expect(combined).toContain('--model-reasoning-effort')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// 2. --print-command with codex harness includes the -c override
// ─────────────────────────────────────────────────────────────────────────────

describe('asp run --print-command: model_reasoning_effort in codex invocation (T-00947)', () => {
  let projectDir: string

  // Set up a minimal project with asp-targets.toml and a pre-composed asp_modules
  // directory so dry-run can load the bundle without a real registry.
  async function setupMinimalProject(): Promise<void> {
    projectDir = join(tmpdir(), `asp-mre-cli-test-${Date.now()}`)
    await mkdir(projectDir, { recursive: true })

    await writeFile(
      join(projectDir, 'asp-targets.toml'),
      `schema = 1

[targets.codex-target]
compose = ["space:test@stable"]

[targets.codex-target.codex]
model = "gpt-5.4"
`
    )

    // Pre-create a minimal asp_modules/codex-target/codex structure so the CLI
    // can load the bundle without needing a real registry install
    const codexHome = join(projectDir, 'asp_modules', 'codex-target', 'codex', 'codex.home')
    await mkdir(codexHome, { recursive: true })
    await mkdir(join(codexHome, 'skills'), { recursive: true })
    await mkdir(join(codexHome, 'prompts'), { recursive: true })

    await writeFile(
      join(codexHome, 'config.toml'),
      'model = "gpt-5.4"\napproval_policy = "on-request"\nsandbox_mode = "workspace-write"\n'
    )
    await writeFile(join(codexHome, 'AGENTS.md'), '<!-- Generated by agent-spaces. -->\n')
    await writeFile(
      join(codexHome, 'manifest.json'),
      JSON.stringify({
        schemaVersion: 1,
        harnessId: 'codex',
        targetName: 'codex-target',
        generatedAt: new Date().toISOString(),
        spaces: [],
        skills: [],
        prompts: [],
        mcpServers: [],
        instructions: [],
      })
    )

    // asp-lock.json is required by the execution layer even in --no-refresh mode
    await writeFile(
      join(projectDir, 'asp-lock.json'),
      JSON.stringify({
        lockfileVersion: 1,
        resolverVersion: 1,
        generatedAt: new Date().toISOString(),
        registry: { type: 'git', url: '/tmp/fake-registry' },
        spaces: {},
        targets: {
          'codex-target': {
            compose: ['space:test@stable'],
            roots: [],
            loadOrder: [],
            envHash: 'sha256:0000000000000000000000000000000000000000000000000000000000000000',
            harnesses: {
              codex: {
                envHash: 'sha256:0000000000000000000000000000000000000000000000000000000000000000',
              },
            },
          },
        },
      })
    )
  }

  async function teardownProject(): Promise<void> {
    await rm(projectDir, { recursive: true, force: true })
  }

  test('--print-command output contains model_reasoning_effort="high" when flag set', async () => {
    await setupMinimalProject()
    try {
      const { stdout, stderr } = runAsp([
        'run',
        'codex-target',
        '--harness',
        'codex',
        '--model-reasoning-effort',
        'high',
        '--print-command',
        '--no-refresh',
        '--project',
        projectDir,
      ])
      const combined = stdout + stderr

      // Should NOT print "unknown option" error
      expect(combined).not.toContain('unknown option')

      // Command output should contain the -c override
      expect(combined).toContain('model_reasoning_effort="high"')
    } finally {
      await teardownProject()
    }
  })

  test('command does not include model_reasoning_effort when flag omitted', async () => {
    await setupMinimalProject()
    try {
      const { stdout, stderr } = runAsp([
        'run',
        'codex-target',
        '--harness',
        'codex',
        '--print-command',
        '--no-refresh',
        '--project',
        projectDir,
      ])
      const combined = stdout + stderr
      expect(combined).not.toContain('model_reasoning_effort')
    } finally {
      await teardownProject()
    }
  })
})
