/**
 * HRC events bridge code generation.
 *
 * The HRC events bridge is a generated Pi extension that forwards Pi lifecycle
 * and stream events to the HRC launch hook.
 */

const HRC_FORWARDED_EVENTS = [
  'before_agent_start',
  'agent_start',
  'agent_end',
  'turn_start',
  'turn_end',
  'message_start',
  'message_update',
  'message_end',
  'tool_execution_start',
  'tool_execution_update',
  'tool_execution_end',
  'session_shutdown',
]

export function generateHrcEventsBridgeCode(): string {
  // Standard event subscriptions: forward (event, ctx) → forward(eventName, payload).
  // The session_start handler is special-cased below to capture sessionId from
  // ctx.sessionManager so HRC can persist it as the runtime continuation key.
  const registrations = HRC_FORWARDED_EVENTS.map(
    (eventName) => `
  pi.on('${eventName}', async (event, _ctx) => {
    await forward('${eventName}', event);
  });`
  ).join('\n')

  return `/**
 * ASP HRC Events Bridge Extension
 *
 * Generated by Agent Spaces - DO NOT EDIT
 *
 * This extension forwards Pi lifecycle and stream events to the HRC launch hook.
 * The session_start handler additionally captures the Pi sessionId so HRC can
 * persist it as the runtime continuation key (enabling deterministic resume).
 */

const { spawn } = require('node:child_process');

function forward(eventName, payload) {
  const hookCli = process.env.HRC_LAUNCH_HOOK_CLI;
  if (!hookCli) return Promise.resolve();

  const envelope = {
    eventName,
    payload: payload ?? {},
  };

  return new Promise((resolve) => {
    const proc = spawn('bun', [hookCli], {
      env: process.env,
      stdio: ['pipe', 'ignore', 'ignore'],
    });

    proc.on('error', () => resolve());
    proc.on('close', () => resolve());

    try {
      proc.stdin.write(JSON.stringify(envelope));
      proc.stdin.end();
    } catch {
      resolve();
    }
  });
}

module.exports = function(pi) {
${registrations}

  pi.on('session_start', async (event, ctx) => {
    let sessionId;
    let sessionFile;
    try {
      sessionId = ctx?.sessionManager?.getSessionId?.();
      sessionFile = ctx?.sessionManager?.getSessionFile?.();
    } catch {
      // ctx unavailable — fall through with undefined
    }
    await forward('session_start', {
      ...(event ?? {}),
      sessionId: sessionId ?? null,
      sessionFile: sessionFile ?? null,
    });
  });
};
`
}
