/**
 * Parity between the embedded manager space, spaces/agent-spaces-manager/,
 * and the canonical copy in the agents root.
 *
 * WHY: `asp repo init` writes the embedded copy (the CLI publishes dist/ only,
 * so it cannot read spaces/ at runtime). The copies drifted silently
 * (T-10291), then forked from the live agents-root copy (T-10369). Both
 * agent-spaces copies are now generated by `just sync-manager-space` from
 * `<agents-root>/spaces/agent-spaces-manager`; these tests make drift loud.
 */

import { describe, expect, test } from 'bun:test'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, relative, resolve } from 'node:path'

import { MANAGER_SPACE_ID, getManagerSpaceFiles } from '../manager-space-content'

const SPACE_DIR = resolve(import.meta.dir, '../../../../../../spaces/agent-spaces-manager')
const CANONICAL_DIR = join(
  process.env['ASP_AGENTS_ROOT'] || join(homedir(), 'praesidium', 'var', 'agents'),
  'spaces',
  MANAGER_SPACE_ID
)
const SYNC_HINT = 'run `just sync-manager-space` in agent-spaces to regenerate the copies'

function listFiles(dir: string): string[] {
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name !== '.DS_Store')
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)))
    .sort()
}

function isExecutable(path: string): boolean {
  return (statSync(path).mode & 0o111) !== 0
}

/** Every way `dir` differs from the embedded copy, empty when identical. */
function driftFrom(dir: string): string[] {
  const embedded = getManagerSpaceFiles()
  const drift: string[] = []
  const embeddedPaths = new Set(embedded.map((file) => file.path))
  for (const path of listFiles(dir))
    if (!embeddedPaths.has(path)) drift.push(`not embedded: ${path}`)
  for (const file of embedded) {
    const onDisk = join(dir, file.path)
    if (!existsSync(onDisk)) {
      drift.push(`missing on disk: ${file.path}`)
    } else if (!Buffer.from(file.content, 'utf8').equals(readFileSync(onDisk))) {
      drift.push(`content differs: ${file.path}`)
    } else if (isExecutable(onDisk) !== (file.executable === true)) {
      drift.push(`executable bit differs: ${file.path}`)
    }
  }
  return drift
}

describe('embedded manager space parity', () => {
  test('embedded copy matches spaces/agent-spaces-manager/ byte for byte', () => {
    expect(driftFrom(SPACE_DIR)).toEqual([])
  })

  // The agents root is host state: CI and other nodes may not have it.
  test.skipIf(!existsSync(join(CANONICAL_DIR, 'space.toml')))(
    `embedded copy matches the canonical ${CANONICAL_DIR}`,
    () => {
      const drift = driftFrom(CANONICAL_DIR)
      if (drift.length > 0) {
        throw new Error(
          `manager space drifted from ${CANONICAL_DIR}; ${SYNC_HINT}:\n  ${drift.join('\n  ')}`
        )
      }
    }
  )
})
